### ISSUE TITLE
[QAIT] Order receipt is not sent to Australian and New Zealand customers via email

### ISSUE THREAD

**Issue by manishaQAIT** [oxipay/oxipay-opencart#4]
Steps to Reproduce:
1. Launch URL: http://13.210.14.116/opencart/ on browser
2. Add any product to a cart and click on Checkout button
3. Select 'Guest checkout' as payment option
4. Enter valid data in billing Details section 
5. Click on Continue button
6. Choose Oxipay as payment method and click on 'Proceed to Oxipay' button
7. Complete the transaction and verify that user is navigated to Thank You page

Actual Result:  Order receipt is not sent to Australian and New Zealand customers via email

Expected Result: Order email receipts should be send to Australian and New Zealand customers

**Comment by sam-flexi** [comment]
Currently investigating this.

**Comment by sam-flexi** [comment]
Issue was with how the OpenCart store was configured. This has now been resolved and we can confirm that email receipts are being sent through when putting orders.
